### ISSUE TITLE
[BUG] Unhandled Error in ExtendedClient

### ISSUE THREAD

**Issue by bowenjw** [ppauel/typescript-discord-bot#4]
**Describe the bug**
The thrown error has code `ENOTDIR`.

**To Reproduce**
1. Place a `.ts` or `.js` file into directories `src\commands`, `src\context_menus` or `src\interactions\buttons`
2. Run command `npm run start`

**Expected behavior**
The files will be ignored in the directory or the files should be read and added to collection.

**Screenshots**
Example Directory
```bash
[ 'example', 'ping.ts' ]
```

Returned error
```bash
Error: ENOTDIR: not a directory, scandir 'C:\Users\user\Documents\GitHub\typescript-discord-bot\src\commands\ping.ts'
    at readdirSync (node:fs:1444:3)
    at C:\Users\user\Documents\GitHub\typescript-discord-bot\src\classes\Client.ts:57:28
    at Array.forEach (<anonymous>)
    at new ExtendedClient (C:\Users\user\Documents\GitHub\typescript-discord-bot\src\classes\Client.ts:55:38)
    at Object.<anonymous> (C:\Users\user\Documents\GitHub\typescript-discord-bot\src\bot.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module.m._compile (C:\Users\user\Documents\GitHub\typescript-discord-bot\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\user\Documents\GitHub\typescript-discord-bot\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1068:32) {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: 'C:\\Users\\user\\Documents\\GitHub\\typescript-discord-bot\\src\\commands\\ping.ts'
}
```

**Comment by ppauel** [comment]
Merged
